### ISSUE TITLE
Interface bug when wrongly sending transaction of an amount over availability 

### ISSUE THREAD

**Issue by gufastian** [RiseVision/rise-wallet#4]
Hello there,
Just wanted to report an interface bug on the web wallet: when sending a transaction of an amount  higher than your wallet availability you get a green message that says "transaction sent".
Which is not true, so you just wait to see the transaction going out while that's not gonna happen.
Thanks for fixing it!

**Comment by vekexasia** [comment]
fixed in https://github.com/RiseVision/rise-wallet/commit/140811331d90f0700d4c54dd0523e11c6c0e10df
